unique_ids:
  assets:
    standard-page.html: GUOPL4ZPXXKRQ73MSBEACGXPSZEFRGYD
    theme.css: X53PPDW7525DEUY7FLIKV5QACOMC677E
  forms:
    Form1: IYZNKVA6OLTQOKKS6AUGHCOPSAIVVHW4
  modules: {}
  scripts: {}
  server_modules: {}
